spring:
  main:
    banner-mode: off
    # ===============================
    # DATABASE
    # ===============================
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres01
      driver-class-name: org.postgresql.Driver
      initialization-mode: always


